// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonC8fc4364DecodeGithubComGodaddyXFreegoProtocolDto(in *jlexer.Lexer, out *System) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "Version":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Version = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC8fc4364EncodeGithubComGodaddyXFreegoProtocolDto(out *jwriter.Writer, in System) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"Version\":"
		out.RawString(prefix)
		out.String(string(in.Version))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v System) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC8fc4364EncodeGithubComGodaddyXFreegoProtocolDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v System) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC8fc4364EncodeGithubComGodaddyXFreegoProtocolDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *System) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC8fc4364DecodeGithubComGodaddyXFreegoProtocolDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *System) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC8fc4364DecodeGithubComGodaddyXFreegoProtocolDto(l, v)
}
func easyjsonC8fc4364DecodeGithubComGodaddyXFreegoProtocolDto1(in *jlexer.Lexer, out *Identify) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "ID":
			if m, ok := out.ID.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.ID.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.ID = in.Interface()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC8fc4364EncodeGithubComGodaddyXFreegoProtocolDto1(out *jwriter.Writer, in Identify) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ID\":"
		out.RawString(prefix[1:])
		if m, ok := in.ID.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.ID.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.ID))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Identify) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC8fc4364EncodeGithubComGodaddyXFreegoProtocolDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Identify) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC8fc4364EncodeGithubComGodaddyXFreegoProtocolDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Identify) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC8fc4364DecodeGithubComGodaddyXFreegoProtocolDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Identify) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC8fc4364DecodeGithubComGodaddyXFreegoProtocolDto1(l, v)
}
func easyjsonC8fc4364DecodeGithubComGodaddyXFreegoProtocolDto2(in *jlexer.Lexer, out *Context) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Identify":
			if in.IsNull() {
				in.Skip()
				out.Identify = nil
			} else {
				if out.Identify == nil {
					out.Identify = new(Identify)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.Identify).UnmarshalEasyJSON(in)
				}
			}
		case "System":
			if in.IsNull() {
				in.Skip()
				out.System = nil
			} else {
				if out.System == nil {
					out.System = new(System)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.System).UnmarshalEasyJSON(in)
				}
			}
		case "Path":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Path = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC8fc4364EncodeGithubComGodaddyXFreegoProtocolDto2(out *jwriter.Writer, in Context) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Identify\":"
		out.RawString(prefix[1:])
		if in.Identify == nil {
			out.RawString("null")
		} else {
			(*in.Identify).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"System\":"
		out.RawString(prefix)
		if in.System == nil {
			out.RawString("null")
		} else {
			(*in.System).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"Path\":"
		out.RawString(prefix)
		out.String(string(in.Path))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Context) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC8fc4364EncodeGithubComGodaddyXFreegoProtocolDto2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Context) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC8fc4364EncodeGithubComGodaddyXFreegoProtocolDto2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Context) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC8fc4364DecodeGithubComGodaddyXFreegoProtocolDto2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Context) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC8fc4364DecodeGithubComGodaddyXFreegoProtocolDto2(l, v)
}
func easyjsonC8fc4364DecodeGithubComGodaddyXFreegoProtocolDto3(in *jlexer.Lexer, out *BaseReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "cmd":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Cmd = string(in.String())
			}
		case "prevID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PrevID = int64(in.Int64())
			}
		case "lastID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastID = int64(in.Int64())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int64(in.Int64())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int64(in.Int64())
			}
		case "countQ":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountQ = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC8fc4364EncodeGithubComGodaddyXFreegoProtocolDto3(out *jwriter.Writer, in BaseReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"cmd\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Cmd))
	}
	{
		const prefix string = ",\"prevID\":"
		out.RawString(prefix)
		out.Int64(int64(in.PrevID))
	}
	{
		const prefix string = ",\"lastID\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastID))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int64(int64(in.Offset))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int64(int64(in.Limit))
	}
	{
		const prefix string = ",\"countQ\":"
		out.RawString(prefix)
		out.Bool(bool(in.CountQ))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BaseReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC8fc4364EncodeGithubComGodaddyXFreegoProtocolDto3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BaseReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC8fc4364EncodeGithubComGodaddyXFreegoProtocolDto3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BaseReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC8fc4364DecodeGithubComGodaddyXFreegoProtocolDto3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BaseReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC8fc4364DecodeGithubComGodaddyXFreegoProtocolDto3(l, v)
}
