// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package ex

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonC0efeda2DecodeGithubComGodaddyXFreegoEx(in *jlexer.Lexer, out *Throw) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Arg":
			if in.IsNull() {
				in.Skip()
				out.Arg = nil
			} else {
				in.Delim('[')
				if out.Arg == nil {
					if !in.IsDelim(']') {
						out.Arg = make([]string, 0, 4)
					} else {
						out.Arg = []string{}
					}
				} else {
					out.Arg = (out.Arg)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = string(in.String())
					}
					out.Arg = append(out.Arg, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "Msg":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Msg = string(in.String())
			}
		case "Url":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Url = string(in.String())
			}
		case "ErrMsg":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ErrMsg = string(in.String())
			}
		case "Code":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Code = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC0efeda2EncodeGithubComGodaddyXFreegoEx(out *jwriter.Writer, in Throw) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Arg\":"
		out.RawString(prefix[1:])
		if in.Arg == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Arg {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.String(string(v3))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"Msg\":"
		out.RawString(prefix)
		out.String(string(in.Msg))
	}
	{
		const prefix string = ",\"Url\":"
		out.RawString(prefix)
		out.String(string(in.Url))
	}
	{
		const prefix string = ",\"ErrMsg\":"
		out.RawString(prefix)
		out.String(string(in.ErrMsg))
	}
	{
		const prefix string = ",\"Code\":"
		out.RawString(prefix)
		out.Int(int(in.Code))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Throw) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC0efeda2EncodeGithubComGodaddyXFreegoEx(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Throw) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC0efeda2EncodeGithubComGodaddyXFreegoEx(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Throw) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC0efeda2DecodeGithubComGodaddyXFreegoEx(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Throw) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC0efeda2DecodeGithubComGodaddyXFreegoEx(l, v)
}
