// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.20.3
// source: rpcx/proto/common_worker.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	D             *anypb.Any             `protobuf:"bytes,1,opt,name=d,proto3" json:"d,omitempty"`  // 数据载体
	N             []byte                 `protobuf:"bytes,2,opt,name=n,proto3" json:"n,omitempty"`  // 随机数
	S             []byte                 `protobuf:"bytes,3,opt,name=s,proto3" json:"s,omitempty"`  // 数据签名
	T             int64                  `protobuf:"varint,4,opt,name=t,proto3" json:"t,omitempty"` // 时间戳
	E             []byte                 `protobuf:"bytes,5,opt,name=e,proto3" json:"e,omitempty"`  // ECDSA签名
	R             string                 `protobuf:"bytes,6,opt,name=r,proto3" json:"r,omitempty"`  // 访问路由
	P             int64                  `protobuf:"varint,7,opt,name=p,proto3" json:"p,omitempty"` // 计划类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonRequest) Reset() {
	*x = CommonRequest{}
	mi := &file_rpcx_proto_common_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonRequest) ProtoMessage() {}

func (x *CommonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcx_proto_common_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonRequest.ProtoReflect.Descriptor instead.
func (*CommonRequest) Descriptor() ([]byte, []int) {
	return file_rpcx_proto_common_worker_proto_rawDescGZIP(), []int{0}
}

func (x *CommonRequest) GetD() *anypb.Any {
	if x != nil {
		return x.D
	}
	return nil
}

func (x *CommonRequest) GetN() []byte {
	if x != nil {
		return x.N
	}
	return nil
}

func (x *CommonRequest) GetS() []byte {
	if x != nil {
		return x.S
	}
	return nil
}

func (x *CommonRequest) GetT() int64 {
	if x != nil {
		return x.T
	}
	return 0
}

func (x *CommonRequest) GetE() []byte {
	if x != nil {
		return x.E
	}
	return nil
}

func (x *CommonRequest) GetR() string {
	if x != nil {
		return x.R
	}
	return ""
}

func (x *CommonRequest) GetP() int64 {
	if x != nil {
		return x.P
	}
	return 0
}

type CommonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	D             *anypb.Any             `protobuf:"bytes,1,opt,name=d,proto3" json:"d,omitempty"`  // 数据载体
	N             []byte                 `protobuf:"bytes,2,opt,name=n,proto3" json:"n,omitempty"`  // 随机数
	S             []byte                 `protobuf:"bytes,3,opt,name=s,proto3" json:"s,omitempty"`  // 数据签名
	T             int64                  `protobuf:"varint,4,opt,name=t,proto3" json:"t,omitempty"` // 时间戳
	E             []byte                 `protobuf:"bytes,5,opt,name=e,proto3" json:"e,omitempty"`  // ECDSA签名
	R             string                 `protobuf:"bytes,6,opt,name=r,proto3" json:"r,omitempty"`  // 访问路由
	P             int64                  `protobuf:"varint,7,opt,name=p,proto3" json:"p,omitempty"` // 计划类型
	C             int64                  `protobuf:"varint,8,opt,name=c,proto3" json:"c,omitempty"` // 响应代码
	M             string                 `protobuf:"bytes,9,opt,name=m,proto3" json:"m,omitempty"`  // 业务消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResponse) Reset() {
	*x = CommonResponse{}
	mi := &file_rpcx_proto_common_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResponse) ProtoMessage() {}

func (x *CommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpcx_proto_common_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResponse.ProtoReflect.Descriptor instead.
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return file_rpcx_proto_common_worker_proto_rawDescGZIP(), []int{1}
}

func (x *CommonResponse) GetD() *anypb.Any {
	if x != nil {
		return x.D
	}
	return nil
}

func (x *CommonResponse) GetN() []byte {
	if x != nil {
		return x.N
	}
	return nil
}

func (x *CommonResponse) GetS() []byte {
	if x != nil {
		return x.S
	}
	return nil
}

func (x *CommonResponse) GetT() int64 {
	if x != nil {
		return x.T
	}
	return 0
}

func (x *CommonResponse) GetE() []byte {
	if x != nil {
		return x.E
	}
	return nil
}

func (x *CommonResponse) GetR() string {
	if x != nil {
		return x.R
	}
	return ""
}

func (x *CommonResponse) GetP() int64 {
	if x != nil {
		return x.P
	}
	return 0
}

func (x *CommonResponse) GetC() int64 {
	if x != nil {
		return x.C
	}
	return 0
}

func (x *CommonResponse) GetM() string {
	if x != nil {
		return x.M
	}
	return ""
}

type TestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestRequest) Reset() {
	*x = TestRequest{}
	mi := &file_rpcx_proto_common_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRequest) ProtoMessage() {}

func (x *TestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcx_proto_common_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRequest.ProtoReflect.Descriptor instead.
func (*TestRequest) Descriptor() ([]byte, []int) {
	return file_rpcx_proto_common_worker_proto_rawDescGZIP(), []int{2}
}

func (x *TestRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TestRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type TestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	ServerTime    int64                  `protobuf:"varint,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestResponse) Reset() {
	*x = TestResponse{}
	mi := &file_rpcx_proto_common_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestResponse) ProtoMessage() {}

func (x *TestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpcx_proto_common_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestResponse.ProtoReflect.Descriptor instead.
func (*TestResponse) Descriptor() ([]byte, []int) {
	return file_rpcx_proto_common_worker_proto_rawDescGZIP(), []int{3}
}

func (x *TestResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

func (x *TestResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

var File_rpcx_proto_common_worker_proto protoreflect.FileDescriptor

const file_rpcx_proto_common_worker_proto_rawDesc = "" +
	"\n" +
	"\x1erpcx/proto/common_worker.proto\x12\n" +
	"pub_worker\x1a\x19google/protobuf/any.proto\"\x87\x01\n" +
	"\rCommonRequest\x12\"\n" +
	"\x01d\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\x01d\x12\f\n" +
	"\x01n\x18\x02 \x01(\fR\x01n\x12\f\n" +
	"\x01s\x18\x03 \x01(\fR\x01s\x12\f\n" +
	"\x01t\x18\x04 \x01(\x03R\x01t\x12\f\n" +
	"\x01e\x18\x05 \x01(\fR\x01e\x12\f\n" +
	"\x01r\x18\x06 \x01(\tR\x01r\x12\f\n" +
	"\x01p\x18\a \x01(\x03R\x01p\"\xa4\x01\n" +
	"\x0eCommonResponse\x12\"\n" +
	"\x01d\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\x01d\x12\f\n" +
	"\x01n\x18\x02 \x01(\fR\x01n\x12\f\n" +
	"\x01s\x18\x03 \x01(\fR\x01s\x12\f\n" +
	"\x01t\x18\x04 \x01(\x03R\x01t\x12\f\n" +
	"\x01e\x18\x05 \x01(\fR\x01e\x12\f\n" +
	"\x01r\x18\x06 \x01(\tR\x01r\x12\f\n" +
	"\x01p\x18\a \x01(\x03R\x01p\x12\f\n" +
	"\x01c\x18\b \x01(\x03R\x01c\x12\f\n" +
	"\x01m\x18\t \x01(\tR\x01m\"E\n" +
	"\vTestRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"E\n" +
	"\fTestResponse\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\x03R\n" +
	"serverTime2M\n" +
	"\fCommonWorker\x12=\n" +
	"\x02Do\x12\x19.pub_worker.CommonRequest\x1a\x1a.pub_worker.CommonResponse\"\x00B\n" +
	"Z\b/rpcx/pbb\x06proto3"

var (
	file_rpcx_proto_common_worker_proto_rawDescOnce sync.Once
	file_rpcx_proto_common_worker_proto_rawDescData []byte
)

func file_rpcx_proto_common_worker_proto_rawDescGZIP() []byte {
	file_rpcx_proto_common_worker_proto_rawDescOnce.Do(func() {
		file_rpcx_proto_common_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpcx_proto_common_worker_proto_rawDesc), len(file_rpcx_proto_common_worker_proto_rawDesc)))
	})
	return file_rpcx_proto_common_worker_proto_rawDescData
}

var file_rpcx_proto_common_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rpcx_proto_common_worker_proto_goTypes = []any{
	(*CommonRequest)(nil),  // 0: pub_worker.CommonRequest
	(*CommonResponse)(nil), // 1: pub_worker.CommonResponse
	(*TestRequest)(nil),    // 2: pub_worker.TestRequest
	(*TestResponse)(nil),   // 3: pub_worker.TestResponse
	(*anypb.Any)(nil),      // 4: google.protobuf.Any
}
var file_rpcx_proto_common_worker_proto_depIdxs = []int32{
	4, // 0: pub_worker.CommonRequest.d:type_name -> google.protobuf.Any
	4, // 1: pub_worker.CommonResponse.d:type_name -> google.protobuf.Any
	0, // 2: pub_worker.CommonWorker.Do:input_type -> pub_worker.CommonRequest
	1, // 3: pub_worker.CommonWorker.Do:output_type -> pub_worker.CommonResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpcx_proto_common_worker_proto_init() }
func file_rpcx_proto_common_worker_proto_init() {
	if File_rpcx_proto_common_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpcx_proto_common_worker_proto_rawDesc), len(file_rpcx_proto_common_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpcx_proto_common_worker_proto_goTypes,
		DependencyIndexes: file_rpcx_proto_common_worker_proto_depIdxs,
		MessageInfos:      file_rpcx_proto_common_worker_proto_msgTypes,
	}.Build()
	File_rpcx_proto_common_worker_proto = out.File
	file_rpcx_proto_common_worker_proto_goTypes = nil
	file_rpcx_proto_common_worker_proto_depIdxs = nil
}
