// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.3
// source: rpcx/proto/common_worker.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CommonWorker_Do_FullMethodName = "/pub_worker.CommonWorker/Do"
)

// CommonWorkerClient is the client API for CommonWorker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommonWorkerClient interface {
	Do(ctx context.Context, in *CommonRequest, opts ...grpc.CallOption) (*CommonResponse, error)
}

type commonWorkerClient struct {
	cc grpc.ClientConnInterface
}

func NewCommonWorkerClient(cc grpc.ClientConnInterface) CommonWorkerClient {
	return &commonWorkerClient{cc}
}

func (c *commonWorkerClient) Do(ctx context.Context, in *CommonRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, CommonWorker_Do_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommonWorkerServer is the server API for CommonWorker service.
// All implementations must embed UnimplementedCommonWorkerServer
// for forward compatibility.
type CommonWorkerServer interface {
	Do(context.Context, *CommonRequest) (*CommonResponse, error)
	mustEmbedUnimplementedCommonWorkerServer()
}

// UnimplementedCommonWorkerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommonWorkerServer struct{}

func (UnimplementedCommonWorkerServer) Do(context.Context, *CommonRequest) (*CommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Do not implemented")
}
func (UnimplementedCommonWorkerServer) mustEmbedUnimplementedCommonWorkerServer() {}
func (UnimplementedCommonWorkerServer) testEmbeddedByValue()                      {}

// UnsafeCommonWorkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommonWorkerServer will
// result in compilation errors.
type UnsafeCommonWorkerServer interface {
	mustEmbedUnimplementedCommonWorkerServer()
}

func RegisterCommonWorkerServer(s grpc.ServiceRegistrar, srv CommonWorkerServer) {
	// If the following call pancis, it indicates UnimplementedCommonWorkerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CommonWorker_ServiceDesc, srv)
}

func _CommonWorker_Do_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommonWorkerServer).Do(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommonWorker_Do_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommonWorkerServer).Do(ctx, req.(*CommonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CommonWorker_ServiceDesc is the grpc.ServiceDesc for CommonWorker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommonWorker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pub_worker.CommonWorker",
	HandlerType: (*CommonWorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Do",
			Handler:    _CommonWorker_Do_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpcx/proto/common_worker.proto",
}
