// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: rpcx/proto/pub_worker.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node int64  `protobuf:"varint,1,opt,name=node,proto3" json:"node,omitempty"`
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
}

func (x *GenerateIdReq) Reset() {
	*x = GenerateIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcx_proto_pub_worker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateIdReq) ProtoMessage() {}

func (x *GenerateIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcx_proto_pub_worker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateIdReq.ProtoReflect.Descriptor instead.
func (*GenerateIdReq) Descriptor() ([]byte, []int) {
	return file_rpcx_proto_pub_worker_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateIdReq) GetNode() int64 {
	if x != nil {
		return x.Node
	}
	return 0
}

func (x *GenerateIdReq) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type GenerateIdRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *GenerateIdRes) Reset() {
	*x = GenerateIdRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcx_proto_pub_worker_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateIdRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateIdRes) ProtoMessage() {}

func (x *GenerateIdRes) ProtoReflect() protoreflect.Message {
	mi := &file_rpcx_proto_pub_worker_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateIdRes.ProtoReflect.Descriptor instead.
func (*GenerateIdRes) Descriptor() ([]byte, []int) {
	return file_rpcx_proto_pub_worker_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateIdRes) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type AuthorizeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *AuthorizeReq) Reset() {
	*x = AuthorizeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcx_proto_pub_worker_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorizeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeReq) ProtoMessage() {}

func (x *AuthorizeReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcx_proto_pub_worker_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeReq.ProtoReflect.Descriptor instead.
func (*AuthorizeReq) Descriptor() ([]byte, []int) {
	return file_rpcx_proto_pub_worker_proto_rawDescGZIP(), []int{2}
}

func (x *AuthorizeReq) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AuthorizeRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token   string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Expired int64  `protobuf:"varint,2,opt,name=expired,proto3" json:"expired,omitempty"`
}

func (x *AuthorizeRes) Reset() {
	*x = AuthorizeRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcx_proto_pub_worker_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorizeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeRes) ProtoMessage() {}

func (x *AuthorizeRes) ProtoReflect() protoreflect.Message {
	mi := &file_rpcx_proto_pub_worker_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeRes.ProtoReflect.Descriptor instead.
func (*AuthorizeRes) Descriptor() ([]byte, []int) {
	return file_rpcx_proto_pub_worker_proto_rawDescGZIP(), []int{3}
}

func (x *AuthorizeRes) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthorizeRes) GetExpired() int64 {
	if x != nil {
		return x.Expired
	}
	return 0
}

type PublicKeyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PublicKeyReq) Reset() {
	*x = PublicKeyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcx_proto_pub_worker_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublicKeyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKeyReq) ProtoMessage() {}

func (x *PublicKeyReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcx_proto_pub_worker_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKeyReq.ProtoReflect.Descriptor instead.
func (*PublicKeyReq) Descriptor() ([]byte, []int) {
	return file_rpcx_proto_pub_worker_proto_rawDescGZIP(), []int{4}
}

type PublicKeyRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey string `protobuf:"bytes,1,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
}

func (x *PublicKeyRes) Reset() {
	*x = PublicKeyRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcx_proto_pub_worker_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublicKeyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKeyRes) ProtoMessage() {}

func (x *PublicKeyRes) ProtoReflect() protoreflect.Message {
	mi := &file_rpcx_proto_pub_worker_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKeyRes.ProtoReflect.Descriptor instead.
func (*PublicKeyRes) Descriptor() ([]byte, []int) {
	return file_rpcx_proto_pub_worker_proto_rawDescGZIP(), []int{5}
}

func (x *PublicKeyRes) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

var File_rpcx_proto_pub_worker_proto protoreflect.FileDescriptor

var file_rpcx_proto_pub_worker_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x72, 0x70, 0x63, 0x78, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x75, 0x62,
	0x5f, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x70,
	0x75, 0x62, 0x5f, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x22, 0x37, 0x0a, 0x0d, 0x47, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x49, 0x64, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69,
	0x6e, 0x64, 0x22, 0x25, 0x0a, 0x0d, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x49, 0x64,
	0x52, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x28, 0x0a, 0x0c, 0x41, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0x3e, 0x0a, 0x0c, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65,
	0x52, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x78, 0x70,
	0x69, 0x72, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x78, 0x70, 0x69,
	0x72, 0x65, 0x64, 0x22, 0x0e, 0x0a, 0x0c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79,
	0x52, 0x65, 0x71, 0x22, 0x2c, 0x0a, 0x0c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79,
	0x52, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65,
	0x79, 0x32, 0xd7, 0x01, 0x0a, 0x09, 0x50, 0x75, 0x62, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x12,
	0x44, 0x0a, 0x0a, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x49, 0x64, 0x12, 0x19, 0x2e,
	0x70, 0x75, 0x62, 0x5f, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x49, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x70, 0x75, 0x62, 0x5f, 0x77,
	0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x49, 0x64,
	0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x09, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69,
	0x7a, 0x65, 0x12, 0x18, 0x2e, 0x70, 0x75, 0x62, 0x5f, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e,
	0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x70,
	0x75, 0x62, 0x5f, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x69, 0x7a, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x09, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x18, 0x2e, 0x70, 0x75, 0x62, 0x5f, 0x77, 0x6f, 0x72, 0x6b,
	0x65, 0x72, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x1a,
	0x18, 0x2e, 0x70, 0x75, 0x62, 0x5f, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x50, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2f,
	0x72, 0x70, 0x63, 0x78, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpcx_proto_pub_worker_proto_rawDescOnce sync.Once
	file_rpcx_proto_pub_worker_proto_rawDescData = file_rpcx_proto_pub_worker_proto_rawDesc
)

func file_rpcx_proto_pub_worker_proto_rawDescGZIP() []byte {
	file_rpcx_proto_pub_worker_proto_rawDescOnce.Do(func() {
		file_rpcx_proto_pub_worker_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpcx_proto_pub_worker_proto_rawDescData)
	})
	return file_rpcx_proto_pub_worker_proto_rawDescData
}

var file_rpcx_proto_pub_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_rpcx_proto_pub_worker_proto_goTypes = []interface{}{
	(*GenerateIdReq)(nil), // 0: pub_worker.GenerateIdReq
	(*GenerateIdRes)(nil), // 1: pub_worker.GenerateIdRes
	(*AuthorizeReq)(nil),  // 2: pub_worker.AuthorizeReq
	(*AuthorizeRes)(nil),  // 3: pub_worker.AuthorizeRes
	(*PublicKeyReq)(nil),  // 4: pub_worker.PublicKeyReq
	(*PublicKeyRes)(nil),  // 5: pub_worker.PublicKeyRes
}
var file_rpcx_proto_pub_worker_proto_depIdxs = []int32{
	0, // 0: pub_worker.PubWorker.GenerateId:input_type -> pub_worker.GenerateIdReq
	2, // 1: pub_worker.PubWorker.Authorize:input_type -> pub_worker.AuthorizeReq
	4, // 2: pub_worker.PubWorker.PublicKey:input_type -> pub_worker.PublicKeyReq
	1, // 3: pub_worker.PubWorker.GenerateId:output_type -> pub_worker.GenerateIdRes
	3, // 4: pub_worker.PubWorker.Authorize:output_type -> pub_worker.AuthorizeRes
	5, // 5: pub_worker.PubWorker.PublicKey:output_type -> pub_worker.PublicKeyRes
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpcx_proto_pub_worker_proto_init() }
func file_rpcx_proto_pub_worker_proto_init() {
	if File_rpcx_proto_pub_worker_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpcx_proto_pub_worker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcx_proto_pub_worker_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateIdRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcx_proto_pub_worker_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorizeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcx_proto_pub_worker_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorizeRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcx_proto_pub_worker_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublicKeyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcx_proto_pub_worker_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublicKeyRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpcx_proto_pub_worker_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpcx_proto_pub_worker_proto_goTypes,
		DependencyIndexes: file_rpcx_proto_pub_worker_proto_depIdxs,
		MessageInfos:      file_rpcx_proto_pub_worker_proto_msgTypes,
	}.Build()
	File_rpcx_proto_pub_worker_proto = out.File
	file_rpcx_proto_pub_worker_proto_rawDesc = nil
	file_rpcx_proto_pub_worker_proto_goTypes = nil
	file_rpcx_proto_pub_worker_proto_depIdxs = nil
}
