// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: component/consul/grpc/idworker.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IdWorkerClient is the client API for IdWorker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IdWorkerClient interface {
	GenerateId(ctx context.Context, in *GenerateIdReq, opts ...grpc.CallOption) (*GenerateIdRes, error)
}

type idWorkerClient struct {
	cc grpc.ClientConnInterface
}

func NewIdWorkerClient(cc grpc.ClientConnInterface) IdWorkerClient {
	return &idWorkerClient{cc}
}

func (c *idWorkerClient) GenerateId(ctx context.Context, in *GenerateIdReq, opts ...grpc.CallOption) (*GenerateIdRes, error) {
	out := new(GenerateIdRes)
	err := c.cc.Invoke(ctx, "/idworker.IdWorker/GenerateId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdWorkerServer is the server API for IdWorker service.
// All implementations must embed UnimplementedIdWorkerServer
// for forward compatibility
type IdWorkerServer interface {
	GenerateId(context.Context, *GenerateIdReq) (*GenerateIdRes, error)
	mustEmbedUnimplementedIdWorkerServer()
}

// UnimplementedIdWorkerServer must be embedded to have forward compatible implementations.
type UnimplementedIdWorkerServer struct {
}

func (UnimplementedIdWorkerServer) GenerateId(context.Context, *GenerateIdReq) (*GenerateIdRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateId not implemented")
}
func (UnimplementedIdWorkerServer) mustEmbedUnimplementedIdWorkerServer() {}

// UnsafeIdWorkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdWorkerServer will
// result in compilation errors.
type UnsafeIdWorkerServer interface {
	mustEmbedUnimplementedIdWorkerServer()
}

func RegisterIdWorkerServer(s grpc.ServiceRegistrar, srv IdWorkerServer) {
	s.RegisterService(&IdWorker_ServiceDesc, srv)
}

func _IdWorker_GenerateId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdWorkerServer).GenerateId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idworker.IdWorker/GenerateId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdWorkerServer).GenerateId(ctx, req.(*GenerateIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

// IdWorker_ServiceDesc is the grpc.ServiceDesc for IdWorker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdWorker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "idworker.IdWorker",
	HandlerType: (*IdWorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateId",
			Handler:    _IdWorker_GenerateId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "component/consul/grpc/idworker.proto",
}
