// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package jwt

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonC16ff783DecodeGithubComGodaddyXFreegoUtilsJwt(in *jlexer.Lexer, out *Subject) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Header":
			if in.IsNull() {
				in.Skip()
				out.Header = nil
			} else {
				if out.Header == nil {
					out.Header = new(Header)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.Header).UnmarshalEasyJSON(in)
				}
			}
		case "Payload":
			if in.IsNull() {
				in.Skip()
				out.Payload = nil
			} else {
				if out.Payload == nil {
					out.Payload = new(Payload)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.Payload).UnmarshalEasyJSON(in)
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC16ff783EncodeGithubComGodaddyXFreegoUtilsJwt(out *jwriter.Writer, in Subject) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Header\":"
		out.RawString(prefix[1:])
		if in.Header == nil {
			out.RawString("null")
		} else {
			(*in.Header).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"Payload\":"
		out.RawString(prefix)
		if in.Payload == nil {
			out.RawString("null")
		} else {
			(*in.Payload).MarshalEasyJSON(out)
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Subject) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC16ff783EncodeGithubComGodaddyXFreegoUtilsJwt(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Subject) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC16ff783EncodeGithubComGodaddyXFreegoUtilsJwt(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Subject) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC16ff783DecodeGithubComGodaddyXFreegoUtilsJwt(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Subject) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC16ff783DecodeGithubComGodaddyXFreegoUtilsJwt(l, v)
}
func easyjsonC16ff783DecodeGithubComGodaddyXFreegoUtilsJwt1(in *jlexer.Lexer, out *Payload) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "sub":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Sub = string(in.String())
			}
		case "aud":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Aud = string(in.String())
			}
		case "iss":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Iss = string(in.String())
			}
		case "dev":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Dev = string(in.String())
			}
		case "jti":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Jti = string(in.String())
			}
		case "ext":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Ext = string(in.String())
			}
		case "iat":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Iat = int64(in.Int64())
			}
		case "exp":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Exp = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC16ff783EncodeGithubComGodaddyXFreegoUtilsJwt1(out *jwriter.Writer, in Payload) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"sub\":"
		out.RawString(prefix[1:])
		out.String(string(in.Sub))
	}
	{
		const prefix string = ",\"aud\":"
		out.RawString(prefix)
		out.String(string(in.Aud))
	}
	{
		const prefix string = ",\"iss\":"
		out.RawString(prefix)
		out.String(string(in.Iss))
	}
	{
		const prefix string = ",\"dev\":"
		out.RawString(prefix)
		out.String(string(in.Dev))
	}
	{
		const prefix string = ",\"jti\":"
		out.RawString(prefix)
		out.String(string(in.Jti))
	}
	{
		const prefix string = ",\"ext\":"
		out.RawString(prefix)
		out.String(string(in.Ext))
	}
	{
		const prefix string = ",\"iat\":"
		out.RawString(prefix)
		out.Int64(int64(in.Iat))
	}
	{
		const prefix string = ",\"exp\":"
		out.RawString(prefix)
		out.Int64(int64(in.Exp))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Payload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC16ff783EncodeGithubComGodaddyXFreegoUtilsJwt1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Payload) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC16ff783EncodeGithubComGodaddyXFreegoUtilsJwt1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Payload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC16ff783DecodeGithubComGodaddyXFreegoUtilsJwt1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Payload) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC16ff783DecodeGithubComGodaddyXFreegoUtilsJwt1(l, v)
}
func easyjsonC16ff783DecodeGithubComGodaddyXFreegoUtilsJwt2(in *jlexer.Lexer, out *Header) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "alg":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Alg = string(in.String())
			}
		case "typ":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Typ = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC16ff783EncodeGithubComGodaddyXFreegoUtilsJwt2(out *jwriter.Writer, in Header) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"alg\":"
		out.RawString(prefix[1:])
		out.String(string(in.Alg))
	}
	{
		const prefix string = ",\"typ\":"
		out.RawString(prefix)
		out.String(string(in.Typ))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Header) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC16ff783EncodeGithubComGodaddyXFreegoUtilsJwt2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Header) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC16ff783EncodeGithubComGodaddyXFreegoUtilsJwt2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Header) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC16ff783DecodeGithubComGodaddyXFreegoUtilsJwt2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Header) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC16ff783DecodeGithubComGodaddyXFreegoUtilsJwt2(l, v)
}
