// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package rabbitmq

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	time "time"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonC80ae7adDecodeGithubComGodaddyXFreegoAmqp(in *jlexer.Lexer, out *Option) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "ex":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Exchange = string(in.String())
			}
		case "qe":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Queue = string(in.String())
			}
		case "kd":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Kind = string(in.String())
			}
		case "ru":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Router = string(in.String())
			}
		case "st":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SigTyp = int(in.Int())
			}
		case "ct":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ConfirmTimeout = time.Duration(in.Int64())
			}
		case "dlx_config":
			if in.IsNull() {
				in.Skip()
				out.DLXConfig = nil
			} else {
				if out.DLXConfig == nil {
					out.DLXConfig = new(DLXConfig)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.DLXConfig).UnmarshalEasyJSON(in)
				}
			}
		case "du":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Durable = bool(in.Bool())
			}
		case "ad":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AutoDelete = bool(in.Bool())
			}
		case "ev":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Exclusive = bool(in.Bool())
			}
		case "ut":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UseTransaction = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC80ae7adEncodeGithubComGodaddyXFreegoAmqp(out *jwriter.Writer, in Option) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ex\":"
		out.RawString(prefix[1:])
		out.String(string(in.Exchange))
	}
	{
		const prefix string = ",\"qe\":"
		out.RawString(prefix)
		out.String(string(in.Queue))
	}
	{
		const prefix string = ",\"kd\":"
		out.RawString(prefix)
		out.String(string(in.Kind))
	}
	{
		const prefix string = ",\"ru\":"
		out.RawString(prefix)
		out.String(string(in.Router))
	}
	{
		const prefix string = ",\"st\":"
		out.RawString(prefix)
		out.Int(int(in.SigTyp))
	}
	{
		const prefix string = ",\"ct\":"
		out.RawString(prefix)
		out.Int64(int64(in.ConfirmTimeout))
	}
	if in.DLXConfig != nil {
		const prefix string = ",\"dlx_config\":"
		out.RawString(prefix)
		(*in.DLXConfig).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"du\":"
		out.RawString(prefix)
		out.Bool(bool(in.Durable))
	}
	{
		const prefix string = ",\"ad\":"
		out.RawString(prefix)
		out.Bool(bool(in.AutoDelete))
	}
	{
		const prefix string = ",\"ev\":"
		out.RawString(prefix)
		out.Bool(bool(in.Exclusive))
	}
	{
		const prefix string = ",\"ut\":"
		out.RawString(prefix)
		out.Bool(bool(in.UseTransaction))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Option) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC80ae7adEncodeGithubComGodaddyXFreegoAmqp(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Option) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC80ae7adEncodeGithubComGodaddyXFreegoAmqp(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Option) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC80ae7adDecodeGithubComGodaddyXFreegoAmqp(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Option) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC80ae7adDecodeGithubComGodaddyXFreegoAmqp(l, v)
}
func easyjsonC80ae7adDecodeGithubComGodaddyXFreegoAmqp1(in *jlexer.Lexer, out *MsgData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "co":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Content = string(in.String())
			}
		case "no":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Nonce = string(in.String())
			}
		case "sg":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Signature = string(in.String())
			}
		case "ex":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Expiration = string(in.String())
			}
		case "ty":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = int64(in.Int64())
			}
		case "dy":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Delay = int64(in.Int64())
			}
		case "rt":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Retries = int64(in.Int64())
			}
		case "op":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Option).UnmarshalEasyJSON(in)
			}
		case "pr":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Priority = uint8(in.Uint8())
			}
		case "du":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Durable = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC80ae7adEncodeGithubComGodaddyXFreegoAmqp1(out *jwriter.Writer, in MsgData) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"co\":"
		out.RawString(prefix[1:])
		out.String(string(in.Content))
	}
	{
		const prefix string = ",\"no\":"
		out.RawString(prefix)
		out.String(string(in.Nonce))
	}
	{
		const prefix string = ",\"sg\":"
		out.RawString(prefix)
		out.String(string(in.Signature))
	}
	{
		const prefix string = ",\"ex\":"
		out.RawString(prefix)
		out.String(string(in.Expiration))
	}
	{
		const prefix string = ",\"ty\":"
		out.RawString(prefix)
		out.Int64(int64(in.Type))
	}
	{
		const prefix string = ",\"dy\":"
		out.RawString(prefix)
		out.Int64(int64(in.Delay))
	}
	{
		const prefix string = ",\"rt\":"
		out.RawString(prefix)
		out.Int64(int64(in.Retries))
	}
	{
		const prefix string = ",\"op\":"
		out.RawString(prefix)
		(in.Option).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"pr\":"
		out.RawString(prefix)
		out.Uint8(uint8(in.Priority))
	}
	{
		const prefix string = ",\"du\":"
		out.RawString(prefix)
		out.Bool(bool(in.Durable))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MsgData) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC80ae7adEncodeGithubComGodaddyXFreegoAmqp1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MsgData) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC80ae7adEncodeGithubComGodaddyXFreegoAmqp1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MsgData) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC80ae7adDecodeGithubComGodaddyXFreegoAmqp1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MsgData) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC80ae7adDecodeGithubComGodaddyXFreegoAmqp1(l, v)
}
func easyjsonC80ae7adDecodeGithubComGodaddyXFreegoAmqp2(in *jlexer.Lexer, out *DLXConfig) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "dlx_exchange":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DlxExchange = string(in.String())
			}
		case "dlx_queue":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DlxQueue = string(in.String())
			}
		case "dlx_router":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DlxRouter = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC80ae7adEncodeGithubComGodaddyXFreegoAmqp2(out *jwriter.Writer, in DLXConfig) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"dlx_exchange\":"
		out.RawString(prefix[1:])
		out.String(string(in.DlxExchange))
	}
	{
		const prefix string = ",\"dlx_queue\":"
		out.RawString(prefix)
		out.String(string(in.DlxQueue))
	}
	{
		const prefix string = ",\"dlx_router\":"
		out.RawString(prefix)
		out.String(string(in.DlxRouter))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v DLXConfig) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC80ae7adEncodeGithubComGodaddyXFreegoAmqp2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DLXConfig) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC80ae7adEncodeGithubComGodaddyXFreegoAmqp2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *DLXConfig) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC80ae7adDecodeGithubComGodaddyXFreegoAmqp2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DLXConfig) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC80ae7adDecodeGithubComGodaddyXFreegoAmqp2(l, v)
}
