// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package node

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson19e19bc5DecodeGithubComGodaddyXFreegoNode(in *jlexer.Lexer, out *PublicKey) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "key":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Key = string(in.String())
			}
		case "tag":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Tag = string(in.String())
			}
		case "noc":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Noc = string(in.String())
			}
		case "sig":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Sig = string(in.String())
			}
		case "exp":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Exp = int64(in.Int64())
			}
		case "usr":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Usr = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson19e19bc5EncodeGithubComGodaddyXFreegoNode(out *jwriter.Writer, in PublicKey) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"key\":"
		out.RawString(prefix[1:])
		out.String(string(in.Key))
	}
	{
		const prefix string = ",\"tag\":"
		out.RawString(prefix)
		out.String(string(in.Tag))
	}
	{
		const prefix string = ",\"noc\":"
		out.RawString(prefix)
		out.String(string(in.Noc))
	}
	{
		const prefix string = ",\"sig\":"
		out.RawString(prefix)
		out.String(string(in.Sig))
	}
	{
		const prefix string = ",\"exp\":"
		out.RawString(prefix)
		out.Int64(int64(in.Exp))
	}
	{
		const prefix string = ",\"usr\":"
		out.RawString(prefix)
		out.Int64(int64(in.Usr))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PublicKey) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson19e19bc5EncodeGithubComGodaddyXFreegoNode(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PublicKey) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson19e19bc5EncodeGithubComGodaddyXFreegoNode(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PublicKey) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson19e19bc5DecodeGithubComGodaddyXFreegoNode(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PublicKey) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson19e19bc5DecodeGithubComGodaddyXFreegoNode(l, v)
}
func easyjson19e19bc5DecodeGithubComGodaddyXFreegoNode1(in *jlexer.Lexer, out *PrivateKey) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "key":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Key = string(in.String())
			}
		case "noc":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Noc = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson19e19bc5EncodeGithubComGodaddyXFreegoNode1(out *jwriter.Writer, in PrivateKey) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"key\":"
		out.RawString(prefix[1:])
		out.String(string(in.Key))
	}
	{
		const prefix string = ",\"noc\":"
		out.RawString(prefix)
		out.String(string(in.Noc))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PrivateKey) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson19e19bc5EncodeGithubComGodaddyXFreegoNode1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PrivateKey) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson19e19bc5EncodeGithubComGodaddyXFreegoNode1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PrivateKey) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson19e19bc5DecodeGithubComGodaddyXFreegoNode1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PrivateKey) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson19e19bc5DecodeGithubComGodaddyXFreegoNode1(l, v)
}
func easyjson19e19bc5DecodeGithubComGodaddyXFreegoNode2(in *jlexer.Lexer, out *JsonResp) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "m":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Message = string(in.String())
			}
		case "d":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Data = string(in.String())
			}
		case "n":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Nonce = string(in.String())
			}
		case "s":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Sign = string(in.String())
			}
		case "e":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Valid = string(in.String())
			}
		case "r":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Router = string(in.String())
			}
		case "c":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Code = int(in.Int())
			}
		case "t":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Time = int64(in.Int64())
			}
		case "p":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Plan = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson19e19bc5EncodeGithubComGodaddyXFreegoNode2(out *jwriter.Writer, in JsonResp) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"m\":"
		out.RawString(prefix[1:])
		out.String(string(in.Message))
	}
	{
		const prefix string = ",\"d\":"
		out.RawString(prefix)
		out.String(string(in.Data))
	}
	{
		const prefix string = ",\"n\":"
		out.RawString(prefix)
		out.String(string(in.Nonce))
	}
	{
		const prefix string = ",\"s\":"
		out.RawString(prefix)
		out.String(string(in.Sign))
	}
	{
		const prefix string = ",\"e\":"
		out.RawString(prefix)
		out.String(string(in.Valid))
	}
	{
		const prefix string = ",\"r\":"
		out.RawString(prefix)
		out.String(string(in.Router))
	}
	{
		const prefix string = ",\"c\":"
		out.RawString(prefix)
		out.Int(int(in.Code))
	}
	{
		const prefix string = ",\"t\":"
		out.RawString(prefix)
		out.Int64(int64(in.Time))
	}
	{
		const prefix string = ",\"p\":"
		out.RawString(prefix)
		out.Int64(int64(in.Plan))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v JsonResp) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson19e19bc5EncodeGithubComGodaddyXFreegoNode2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v JsonResp) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson19e19bc5EncodeGithubComGodaddyXFreegoNode2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *JsonResp) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson19e19bc5DecodeGithubComGodaddyXFreegoNode2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *JsonResp) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson19e19bc5DecodeGithubComGodaddyXFreegoNode2(l, v)
}
func easyjson19e19bc5DecodeGithubComGodaddyXFreegoNode3(in *jlexer.Lexer, out *JsonBody) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "d":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Data = string(in.String())
			}
		case "n":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Nonce = string(in.String())
			}
		case "s":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Sign = string(in.String())
			}
		case "e":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Valid = string(in.String())
			}
		case "r":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Router = string(in.String())
			}
		case "t":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Time = int64(in.Int64())
			}
		case "p":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Plan = int64(in.Int64())
			}
		case "u":
			if in.IsNull() {
				in.Skip()
			} else {
				out.User = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson19e19bc5EncodeGithubComGodaddyXFreegoNode3(out *jwriter.Writer, in JsonBody) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"d\":"
		out.RawString(prefix[1:])
		out.String(string(in.Data))
	}
	{
		const prefix string = ",\"n\":"
		out.RawString(prefix)
		out.String(string(in.Nonce))
	}
	{
		const prefix string = ",\"s\":"
		out.RawString(prefix)
		out.String(string(in.Sign))
	}
	{
		const prefix string = ",\"e\":"
		out.RawString(prefix)
		out.String(string(in.Valid))
	}
	{
		const prefix string = ",\"r\":"
		out.RawString(prefix)
		out.String(string(in.Router))
	}
	{
		const prefix string = ",\"t\":"
		out.RawString(prefix)
		out.Int64(int64(in.Time))
	}
	{
		const prefix string = ",\"p\":"
		out.RawString(prefix)
		out.Int64(int64(in.Plan))
	}
	{
		const prefix string = ",\"u\":"
		out.RawString(prefix)
		out.Int64(int64(in.User))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v JsonBody) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson19e19bc5EncodeGithubComGodaddyXFreegoNode3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v JsonBody) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson19e19bc5EncodeGithubComGodaddyXFreegoNode3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *JsonBody) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson19e19bc5DecodeGithubComGodaddyXFreegoNode3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *JsonBody) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson19e19bc5DecodeGithubComGodaddyXFreegoNode3(l, v)
}
