// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package sqlc

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson903aeb83DecodeGithubComGodaddyXFreegoOrmxSqlc(in *jlexer.Lexer, out *Limit) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int64(in.Int64())
			}
		case "total":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Total = int64(in.Int64())
			}
		case "lastID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastID = int64(in.Int64())
			}
		case "prevID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PrevID = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson903aeb83EncodeGithubComGodaddyXFreegoOrmxSqlc(out *jwriter.Writer, in Limit) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.Limit))
	}
	{
		const prefix string = ",\"total\":"
		out.RawString(prefix)
		out.Int64(int64(in.Total))
	}
	{
		const prefix string = ",\"lastID\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastID))
	}
	{
		const prefix string = ",\"prevID\":"
		out.RawString(prefix)
		out.Int64(int64(in.PrevID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Limit) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson903aeb83EncodeGithubComGodaddyXFreegoOrmxSqlc(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Limit) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson903aeb83EncodeGithubComGodaddyXFreegoOrmxSqlc(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Limit) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson903aeb83DecodeGithubComGodaddyXFreegoOrmxSqlc(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Limit) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson903aeb83DecodeGithubComGodaddyXFreegoOrmxSqlc(l, v)
}
